server:
  port: ${SERVER_PORT}
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 10s
  read_header_timeout: 5s
  compress_size: 5

gitlab:
  webhook_secret: ${GITLAB_WEBHOOK_SECRET}

telegram:
  bot_token: ${TELEGRAM_BOT_TOKEN}
  timeout: 10s
  max_retries: 3

log_level: ${LOG_LEVEL}
